### ISSUE TITLE
NotImplementedException: Netly Message framing prefix not found.

### ISSUE THREAD

**Issue by gbradburn** [alec1o/Byter#33]
I'm getting this error when opening a TCP connection. What am I missing?
Also, it looks like Host can only take an IP address not a named address (e.g. someaddr.com). Is that correct?

**Comment by alec1o** [comment]
Hi, please give me the log

**Comment by alec1o** [comment]
The host use ip only, but I'm thinked about implement a way to find host from domain name, but I discard this solution

**Comment by alec1o** [comment]
https://github.com/alec1o/Netly/issues/37

**Comment by alec1o** [comment]
Yes it's correct because Host only accept ip address, I think about implement that but I discard this ideia because is more good to netly make focus on ip address, the reason was: then you find domain first you need network, 2nd you must process this domain on background,

 what dns netly will choose IPv4 or IPv6 ip?
If you have more than one IP what choose? First or Last?
Is example of things that you must config, implement this should make complex host usage.

But is must fast found ip from a domain in c# and pas this address and ip to netly.

```cs
var url = "http://oldschool.runescape.com/game?world=321";
Uri myUri = new Uri(url);
var ip = Dns.GetHostAddresses(myUri.Host)[0];

Host host = new Host(ip, $port)
```
